### ISSUE TITLE
I had a few problems when using your extension

### ISSUE THREAD

**Issue by aau8** [moyus/laravel-mix-nunjucks#14]
Проблема была в функции run(), а именно в формате пути. Два последних она возвращала с двумя косыми чертами.
![image](https://user-images.githubusercontent.com/55375066/182168523-c1dd885c-4761-4987-9bcc-abef025c90ee.png)
![image](https://user-images.githubusercontent.com/55375066/182168665-2a38a353-a67c-4a62-820d-6c05e66d0e3c.png)

Помогло дублирование replace, как у первой строки
![image](https://user-images.githubusercontent.com/55375066/182169159-d0c72906-a5d4-4cee-989b-92a96377bc2a.png)

**Comment by aau8** [comment]
Here are some more problems that I have:
1. In the run function, not only files with the .njk extension were compiled, but all files. Which is why I received files from style.css at the output - style.html , from index.js - index.html etc.
2. In the watch function, changes were tracked not only in .njk files, but in all files, i.e. when I updated the style.scss file, your plugin started working
3. I didn't find a setting for the plugin to tell it where my nunjucks templates are, so as not to specify the whole path every time. I keep all the templates in the _njk folder, so I wanted nunjucks to take everything from there. Perhaps the extension has a setting that does this, please tell me what it's called.

I implemented all this in a separate fork - https://github.com/artemyg0811/laravel-mix-nunjucks
I hope some of this will be useful. I'm making a starter template for layout and your extension has helped a lot to work with nunjucks, but at the moment, I can't install it directly, because it doesn't perform the individual functions I need. It would be great if you made changes to your extensions based on my suggestions)))

The starting template in which I use your extension is https://github.com/artemyg0811/dismal-html

**Comment by moyus** [comment]
Sorry for the late, I will fix it soon.

**Comment by moyus** [comment]
- Windows platform path issue has been fixed in v1.2.3
- You should only put nunjuck and markdown files under source template directory, place your other assets in a different directory would just be fine
