### ISSUE TITLE
Files versioning not working in production mode

### ISSUE THREAD

**Issue by Olivier-Rasquin** [moyus/laravel-mix-nunjucks#15]
Hi,

I had some issues on my project using `mix.version()` and `{% mix '/js/app.js' %}`.
The versioning was working fine on dev mode ('mix watch'), but not on production ('npx mix --production').

One of my colleague figured out that downgrading the laravel-mix-nunjucks version from 1.1.0 to 0.3.0 would solved the issue, and make the versioning work for both dev and production mode.

So there's probably something in the newest versions of your package that's preventing files versioning from working correctly, could you please have a look at it?

Thank you!

**Comment by moyus** [comment]
I will take a look later, thanks for raising up this issue.

**Comment by moyus** [comment]
Files versioning bug has been fixed, please update to v1.2.3

**Comment by Olivier-Rasquin** [comment]
Working great, thank you!
