### ISSUE TITLE
Includes not triggering compile 

### ISSUE THREAD

**Issue by sueharaluke** [moyus/laravel-mix-nunjucks#17]
Looks like the latest version `1.2.3` isn't compiling when only includes/partials change.  
As a work around, I'm using `laravel-mix-nunjucks@1.2.0-beta.1` that was suggested in issue #8. 
But using underscore on directory name is not enough, I need to use on the file name as well, otherwise includes/partials also get compiled as html files.

Just a heads up.  
Thanks for the plugin !

**Comment by moyus** [comment]
Will look into it later. 👀

**Comment by moyus** [comment]
Partials change has been fixed in `v1.2.4`. And you can use `mix.njk('tests/src/**/*.njk', 'public')` to only watch and compile nunjucks files.
